apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-kraft-sts
  labels:
    app: kafka-kraft-app
  namespace: kafka-kraft
spec:
  serviceName: kafka-kraft-svc
  replicas: 3
  selector:
    matchLabels:
      app: kafka-kraft-app
  volumeClaimTemplates:
  - metadata:
      name: kafka-kraft-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "kafka-kraft-sc"
      resources:
        requests:
          storage: 50Gi
  template:
    metadata:
      labels:
        app: kafka-kraft-app
    spec:
      containers:
        - name: kafka-kraft-app-container
          image: syspago/kafka-kraft:1.0.0
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: REPLICAS
              value: '3'
            - name: SERVICE
              value: kafka-kraft-svc
            - name: NAMESPACE
              value: kafka-kraft
            - name: SHARE_DIR
              value: /mnt/kafka-kraft
          volumeMounts:
            - name: kafka-kraft-pvc
              mountPath: /mnt/kafka-kraft
#### You only want Kafka running on an independent node and don't want it to mix with other application pods.
#      tolerations:
#      - key: "app.stateful/component"
#        operator: "Equal"
#        value: "kafka-broker"
#        effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app.stateful/component"
                operator: In
                values:
                - "kafka-kraft-broker"
            topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "app.stateful/component"
                operator: In
                values:
                - "kafka-kraft-broker"
#### In any public cloud, a zone groups together resources that may fail together
#      topologySpreadConstraints:
#      - maxSkew: 1
#        topologyKey: topology.kubernetes.io/zone
#        whenUnsatisfiable: DoNotSchedule
#        labelSelector:
#          matchLabels:
#            app: kafka-app
