apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kafka-kraft-sc
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-ssd
  csi.storage.k8s.io/fstype: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
